// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OlympicGames.Models;

namespace OlympicGames.Migrations
{
    [DbContext(typeof(CountryContext))]
    partial class CountryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("OlympicGames.Models.Category", b =>
                {
                    b.Property<string>("CategoryId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = "I",
                            Name = "Indoor"
                        },
                        new
                        {
                            CategoryId = "O",
                            Name = "Outdoor"
                        });
                });

            modelBuilder.Entity("OlympicGames.Models.Country", b =>
                {
                    b.Property<string>("CountryId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CategoryId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FlagImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GameId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SportId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("CountryId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("GameId");

                    b.HasIndex("SportId");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            CountryId = "CAN",
                            CategoryId = "I",
                            FlagImage = "CAN.png",
                            GameId = "WO",
                            Name = "Canada",
                            SportId = "Cur"
                        },
                        new
                        {
                            CountryId = "SWE",
                            CategoryId = "I",
                            FlagImage = "SWE.png",
                            GameId = "WO",
                            Name = "Sweden",
                            SportId = "Cur"
                        },
                        new
                        {
                            CountryId = "GB",
                            CategoryId = "I",
                            FlagImage = "GB.png",
                            GameId = "WO",
                            Name = "Great Britain",
                            SportId = "Cur"
                        },
                        new
                        {
                            CountryId = "JAM",
                            CategoryId = "O",
                            FlagImage = "JAM.png",
                            GameId = "WO",
                            Name = "Jamaica",
                            SportId = "Bob"
                        },
                        new
                        {
                            CountryId = "ITA",
                            CategoryId = "O",
                            FlagImage = "ITA.png",
                            GameId = "WO",
                            Name = "Italy",
                            SportId = "Bob"
                        },
                        new
                        {
                            CountryId = "JAP",
                            CategoryId = "O",
                            FlagImage = "JAP.png",
                            GameId = "WO",
                            Name = "Japan",
                            SportId = "Bob"
                        },
                        new
                        {
                            CountryId = "GER",
                            CategoryId = "I",
                            FlagImage = "GER.png",
                            GameId = "SO",
                            Name = "Germany",
                            SportId = "Div"
                        },
                        new
                        {
                            CountryId = "CHI",
                            CategoryId = "I",
                            FlagImage = "CHI.png",
                            GameId = "SO",
                            Name = "China",
                            SportId = "Div"
                        },
                        new
                        {
                            CountryId = "MEX",
                            CategoryId = "I",
                            FlagImage = "MEX.png",
                            GameId = "SO",
                            Name = "Mexico",
                            SportId = "Div"
                        },
                        new
                        {
                            CountryId = "BRA",
                            CategoryId = "O",
                            FlagImage = "BRA.png",
                            GameId = "SO",
                            Name = "Brazil",
                            SportId = "RCyc"
                        },
                        new
                        {
                            CountryId = "NET",
                            CategoryId = "O",
                            FlagImage = "NET.png",
                            GameId = "SO",
                            Name = "Netherlands",
                            SportId = "RCyc"
                        },
                        new
                        {
                            CountryId = "USA",
                            CategoryId = "O",
                            FlagImage = "USA.png",
                            GameId = "SO",
                            Name = "USA",
                            SportId = "RCyc"
                        },
                        new
                        {
                            CountryId = "THA",
                            CategoryId = "I",
                            FlagImage = "THA.png",
                            GameId = "P",
                            Name = "Thailand",
                            SportId = "Arc"
                        },
                        new
                        {
                            CountryId = "URU",
                            CategoryId = "I",
                            FlagImage = "URU.png",
                            GameId = "P",
                            Name = "Uruguay",
                            SportId = "Arc"
                        },
                        new
                        {
                            CountryId = "UKR",
                            CategoryId = "I",
                            FlagImage = "UKR.png",
                            GameId = "P",
                            Name = "Ukraine",
                            SportId = "Arc"
                        },
                        new
                        {
                            CountryId = "AUS",
                            CategoryId = "O",
                            FlagImage = "AUS.png",
                            GameId = "P",
                            Name = "Austria",
                            SportId = "CanSpr"
                        },
                        new
                        {
                            CountryId = "PAK",
                            CategoryId = "O",
                            FlagImage = "PAK.png",
                            GameId = "P",
                            Name = "Pakistan",
                            SportId = "CanSpr"
                        },
                        new
                        {
                            CountryId = "ZIM",
                            CategoryId = "O",
                            FlagImage = "ZIM.png",
                            GameId = "P",
                            Name = "Zimbabwe",
                            SportId = "CanSpr"
                        },
                        new
                        {
                            CountryId = "FRA",
                            CategoryId = "I",
                            FlagImage = "FRA.png",
                            GameId = "YSO",
                            Name = "France",
                            SportId = "BreDan"
                        },
                        new
                        {
                            CountryId = "CYP",
                            CategoryId = "I",
                            FlagImage = "CYP.png",
                            GameId = "YSO",
                            Name = "Cyprus",
                            SportId = "BreDan"
                        },
                        new
                        {
                            CountryId = "RUS",
                            CategoryId = "I",
                            FlagImage = "RUS.png",
                            GameId = "YSO",
                            Name = "Russia",
                            SportId = "BreDan"
                        },
                        new
                        {
                            CountryId = "FIN",
                            CategoryId = "O",
                            FlagImage = "FIN.png",
                            GameId = "YSO",
                            Name = "Finland",
                            SportId = "SkaBoa"
                        },
                        new
                        {
                            CountryId = "SLO",
                            CategoryId = "O",
                            FlagImage = "SLO.png",
                            GameId = "YSO",
                            Name = "Slovakia",
                            SportId = "SkaBoa"
                        },
                        new
                        {
                            CountryId = "POR",
                            CategoryId = "O",
                            FlagImage = "POR.png",
                            GameId = "YSO",
                            Name = "Portugal",
                            SportId = "SkaBoa"
                        });
                });

            modelBuilder.Entity("OlympicGames.Models.Game", b =>
                {
                    b.Property<string>("GameId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GameId");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            GameId = "P",
                            Name = "Paralympics"
                        },
                        new
                        {
                            GameId = "SO",
                            Name = "Summer Olympics"
                        },
                        new
                        {
                            GameId = "WO",
                            Name = "Winter Olympics"
                        },
                        new
                        {
                            GameId = "YSO",
                            Name = "Youth Olympic Games"
                        });
                });

            modelBuilder.Entity("OlympicGames.Models.Sport", b =>
                {
                    b.Property<string>("SportId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SportId");

                    b.ToTable("Sports");

                    b.HasData(
                        new
                        {
                            SportId = "Cur",
                            Name = "Curling"
                        },
                        new
                        {
                            SportId = "Bob",
                            Name = "Bobsleigh"
                        },
                        new
                        {
                            SportId = "Div",
                            Name = "Diving"
                        },
                        new
                        {
                            SportId = "RCyc",
                            Name = "Road Cycling"
                        },
                        new
                        {
                            SportId = "Arc",
                            Name = "Archery"
                        },
                        new
                        {
                            SportId = "CanSpr",
                            Name = "Canoe Sprint"
                        },
                        new
                        {
                            SportId = "BreDan",
                            Name = "Breakdancing"
                        },
                        new
                        {
                            SportId = "SkaBoa",
                            Name = "Skateboarding"
                        });
                });

            modelBuilder.Entity("OlympicGames.Models.Country", b =>
                {
                    b.HasOne("OlympicGames.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId");

                    b.HasOne("OlympicGames.Models.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameId");

                    b.HasOne("OlympicGames.Models.Sport", "Sport")
                        .WithMany()
                        .HasForeignKey("SportId");
                });
#pragma warning restore 612, 618
        }
    }
}
